=== am78/myTimes/build/Debug-iphoneos/TaskTracker.app/mytimes-model.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
	targetNamespace="mytimes" version="1.1" xmlns:tns="mytimes"
	elementFormDefault="qualified">

	<element name="Data" type="tns:Data"></element>

	<complexType name="Project">
		<sequence>
			<element name="Task" type="tns:Task" maxOccurs="unbounded"
				minOccurs="0">
			</element>
		</sequence>
		<attribute name="name" type="string" use="required"></attribute>
		<attribute name="description" type="string" use="optional"></attribute>
		<attribute name="editable" type="boolean" use="optional"></attribute>
	</complexType>

	<complexType name="Task">
		<sequence>
			<element name="WorkUnit" type="tns:WorkUnit" minOccurs="0"
				maxOccurs="unbounded">
			</element>
			<element name="Attributes" type="tns:Attributes" minOccurs="0" maxOccurs="1" />
		</sequence>
		<attribute name="name" type="string" use="required"></attribute>
		<attribute name="description" type="string" use="optional"></attribute>
		<attribute name="editable" type="boolean" use="optional"></attribute>
	</complexType>
	
	<complexType name="Attributes">
		<sequence>
			<element name="Attribute" type="tns:Attribute" minOccurs="0"	maxOccurs="unbounded" />
		</sequence>
	</complexType>

	<complexType name="WorkUnit">
		<attribute name="description" type="string" use="optional"></attribute>
		<attribute name="startTime" type="dateTime" use="required"></attribute>
		<attribute name="duration" type="int" use="required"></attribute>
		<attribute name="pause" type="int" use="required"></attribute>
		<attribute name="running" type="boolean" use="required"></attribute>
		<attribute name="chargeable" type="boolean" use="required"></attribute>
	</complexType>

	<complexType name="Data">
		<sequence>
			<element name="Project" type="tns:Project" minOccurs="0"
				maxOccurs="unbounded">
			</element>
		</sequence>
	</complexType>

	<complexType name="Attribute">
		<sequence>
			<element name="key" type="string" minOccurs="1"
				maxOccurs="1" />
			<element name="datatype" minOccurs="1" maxOccurs="1">
				<simpleType>
					<restriction base="string">
						<enumeration value="string"></enumeration>
						<enumeration value="int"></enumeration>
						<enumeration value="long"></enumeration>
						<enumeration value="boolean"></enumeration>
						<enumeration value="date"></enumeration>
						<enumeration value="float"></enumeration>
						<enumeration value="double"></enumeration>
					</restriction>
				</simpleType>
			</element>
			<element name="value" type="anySimpleType"></element>
		</sequence>
	</complexType>
</schema>

=== am78/myTimes/model/instance1.xml
<?xml version="1.0" encoding="UTF-8"?>
<Data xmlns="mytimes"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
 xsi:schemaLocation="mytimes http://iphone.anteboth.com/mytimes/xml/mytimes-model.xsd">
    <Project name="name1" description="description1">
        <Task name="name3" description="description3">
            <WorkUnit description="description5" startTime="2006-05-04T18:13:51.0Z" duration="0" pause="0" running="false"
                 chargeable="false"/>
            <WorkUnit description="description7" startTime="2006-05-04T18:13:51.0Z" duration="0" pause="0" running="false"
                 chargeable="false"/>
        </Task>
        <Task name="name5" description="description9">
            <WorkUnit description="description11" startTime="2006-05-04T18:13:51.0Z" duration="0" pause="0" running="false"
                 chargeable="false"/>
            <WorkUnit description="description13" startTime="2006-05-04T18:13:51.0Z" duration="0" pause="0" running="false"
                 chargeable="false"/>
        </Task>
    </Project>
    <Project name="name7" description="description15">
        <Task name="name9" description="description17">
            <WorkUnit description="description19" startTime="2006-05-04T18:13:51.0Z" duration="0" pause="0" running="false"
                 chargeable="false"/>
            <WorkUnit description="description21" startTime="2006-05-04T18:13:51.0Z" duration="0" pause="0" running="false"
                 chargeable="false"/>
        </Task>
        <Task name="name11" description="description23">
            <WorkUnit description="description25" startTime="2006-05-04T18:13:51.0Z" duration="0" pause="0" running="false"
                 chargeable="false"/>
            <WorkUnit description="description27" startTime="2006-05-04T18:13:51.0Z" duration="0" pause="0" running="false"
                 chargeable="false"/>
        </Task>
    </Project>
</Data>

=== am78/myTimes/model/NewFile.xml
<?xml version="1.0" encoding="UTF-8"?>
<Data xmlns="mytimes" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="mytimes mytimes-model.xsd ">
  <Project description="" editable="true" name="test projekt">
    <Task description="" editable="true" name="Teilprojekt">
      <WorkUnit chargeable="true" description="" duration="0" pause="0" running="true" startTime="2001-12-31T12:00:00"/>
      <Attributes>
        <Attribute>
          <key>key</key>
          <datatype>boolean</datatype>
          <value>true</value>
        </Attribute>
      </Attributes>
    </Task>
  </Project>
</Data>
